# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0208_add_realm_night_logo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmauditlog',
            name='new_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='realmauditlog',
            name='old_data',
            field=models.TextField(null=True),
        ),
    ]
