# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0209_auto_20190308_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realmauditlog',
            old_name='new_data',
            new_name='new_value',
        ),
        migrations.RenameField(
            model_name='realmauditlog',
            old_name='old_data',
            new_name='old_value',
        ),
    ]
